version: '3.9'

services:
  app-dev:
    # สร้าง image จาก Dockerfile ในโฟลเดอร์ปัจจุบัน
    build:
      context: .
    container_name: flask-app-dev-instance

    # map port: host 5002 -> container 5000
    ports:
      - "5002:5000"

    # เชื่อมโค้ดจาก host เข้า container แบบ real-time
    volumes:
      - ./:/app

    environment:
      # Flask configuration
      FLASK_APP: app.py
      FLASK_DEBUG: "1"               # auto-reload
      PYTHONDONTWRITEBYTECODE: "1"   # ไม่สร้าง .pyc

    # คำสั่งรัน container
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
             flask run --host=0.0.0.0 --port=5000"